SKILLS = ["Python", "Machine Learning", "Web Development", "SQL", "DSA"]
# (skill, question, options, correct option index)
QUESTIONS = [
 ("Python","What is the output of type([])?",["list","tuple","dict","set"],0),
 ("Python","Which keyword defines a function in Python?",["func","def","lambda","fun"],1),
 ("Python","What is len('CareerPilot')?",["10","11","12","9"],1),
 ("Python","Which of these is immutable?",["list","dict","tuple","set"],2),
 ("Python","What is 7 // 2 in Python?",["3.5","3","4","2"],1),
 ("Python","Which command creates a virtual environment?",["pip install venv","python -m venv env","python venv run","pip env new"],1),
 ("Machine Learning","Which is a supervised algorithm?",["K-Means","Random Forest","PCA","DBSCAN"],1),
 ("Machine Learning","Overfitting means the model...",["Does well on training data but poorly on new data","Does poorly everywhere","Trains too fast","Has too few features"],0),
 ("Machine Learning","KNN stands for?",["K-Nearest Neighbors","Key Neural Network","K-Normal Node","Known Nearest Number"],0),
 ("Machine Learning","Naive Bayes is based on?",["Bayes' theorem","Gradient descent","Backpropagation","Clustering"],0),
 ("Machine Learning","A Random Forest is a group of?",["Decision Trees","Neural layers","Clusters","Regressions only"],0),
 ("Machine Learning","Which is a classification metric?",["RMSE","Accuracy","MAE","R-squared"],1),
 ("Web Development","HTML stands for?",["HyperText Markup Language","High Text Machine Language","HyperTool Multi Language","Home Text Markup Level"],0),
 ("Web Development","Which CSS property changes text color?",["font-style","color","text-size","background"],1),
 ("Web Development","Which HTTP method is used to fetch data?",["POST","PUT","GET","DELETE"],2),
 ("Web Development","Which is a Python web framework?",["Flask","React","Angular","Laravel"],0),
 ("Web Development","Which JavaScript keyword declares a constant?",["var","let","const","static"],2),
 ("Web Development","HTTP status 404 means?",["Server error","Not Found","OK","Forbidden"],1),
 ("SQL","Which command retrieves data?",["GET","SELECT","FETCH","PULL"],1),
 ("SQL","Which clause filters rows?",["WHERE","GROUP","ORDER","LIMIT"],0),
 ("SQL","Which keyword removes duplicate rows?",["UNIQUE ROWS","DISTINCT","REMOVE","SINGLE"],1),
 ("SQL","Which function counts rows?",["SUM()","COUNT(*)","TOTAL()","LEN()"],1),
 ("SQL","Which JOIN returns only matching rows from both tables?",["LEFT JOIN","FULL JOIN","INNER JOIN","CROSS JOIN"],2),
 ("SQL","Which clause sorts the result?",["SORT","ORDER BY","ARRANGE","GROUP BY"],1),
 ("DSA","Which structure follows LIFO?",["Queue","Stack","Array","Graph"],1),
 ("DSA","Time complexity of binary search?",["O(n)","O(log n)","O(n^2)","O(1)"],1),
 ("DSA","Which structure follows FIFO?",["Stack","Tree","Queue","Heap"],2),
 ("DSA","Worst-case time of bubble sort?",["O(n log n)","O(n)","O(n^2)","O(log n)"],2),
 ("DSA","Average lookup time in a hash table?",["O(1)","O(n)","O(log n)","O(n^2)"],0),
 ("DSA","Which traversal uses a queue?",["DFS","BFS","Inorder","Preorder"],1),
]
